name: example-workflow
on: [push]
jobs:
  explore-first-github-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Example-workflow autmatically triggered by ${{github.event_name}}."
      - run: echo "Example-workflow running on ${{runner.os}}."
      - name: Check out repo code
        uses: actions/checkout@v2
